chore(snackbars): add paparazzi tests
Decathlon/vitamin-compose pull request #131
Opened 2023-04-07 12:34 UTC by FDELAHA24

## Changes description 🧑‍💻

Add paparazzi tests for Snackbars

## Context 🤔

#94

## Checklist ✅

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Screenshots 📸

## Other info 👋

2023-04-07 12:53 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/c0c14542-ba1b-4392-a97b-6bff0977beb9/artifact/b8bdbe6659ee23f7/p/33df77541aaf0f50d767572849226413

2023-04-07 13:07 UTC, ManonPolle requested changes

2023-04-20 06:51 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/88b25c83-7d09-4e1c-85d1-32ce6ab1a748/artifact/40372c1759968e63/p/b30a3036ac968176c899f4bdd02c2a82

2023-04-20 12:00 UTC, ManonPolle approved these changes

2023-04-20 13:56 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/5890c65c-5aff-4f9f-865f-f5da04c37588/artifact/807a0a8500960a16/p/21db2dd3d2c4c565f6f75ab6fd6b7a4c

2023-04-20 13:57 UTC, merged