chore(prices): add paparazzi tests
Decathlon/vitamin-compose pull request #132
Opened 2023-04-07 13:05 UTC by FDELAHA24

## Changes description 🧑‍💻

Add paparazzi tests for Prices

## Context 🤔

#89 

## Checklist ✅

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Screenshots 📸

## Other info 👋

2023-04-07 13:09 UTC, ManonPolle requested changes

2023-04-07 13:09 UTC, ManonPolle commented on prices/src/test/kotlin/com/decathlon/vitamin/compose/prices/utils/PriceVariantsFactory.kt
> +        size: PriceSizes,
size should be above modifier as there is no default value

2023-04-07 13:23 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/271c47a4-6d15-4315-a3a3-4e95a4473b18/artifact/800abe3e0f0e3c14/p/694b6984b0fe381285ec03d35eaa3a80

2023-04-20 06:51 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/d7f8e0cd-ad72-458b-a666-18ba61035990/artifact/694196c4a242b714/p/f61138084f8dc13c19d453d0eaf229b5

2023-04-20 11:58 UTC, ManonPolle approved these changes

2023-04-20 13:29 UTC, merged