Create convention file to follow in all contributions
Decathlon/vitamin-compose pull request #16
Opened 2022-06-02 15:06 UTC by GerardPaligot

## Changes description 🧑‍💻

[chore: Update Compose, Kotlin and AGP dependencies.](https://github.com/Decathlon/vitamin-compose/commit/4b2b47c66329e3931945fde4e2bac7ab1cf28a06)
 
[refactor(foundation): Move ripple to the Vitamin theme](https://github.com/Decathlon/vitamin-compose/commit/85bbd0979a89c524ce98eb4902067f697d3c861d)

[refactor(buttons): Migrate to the new composable contract convention](https://github.com/Decathlon/vitamin-compose/commit/ad64e3a8f0d2585c36282e6db6ff756629b23807)

[docs: Add conventions about components.](https://github.com/Decathlon/vitamin-compose/commit/c50263046a9be7bd5218d7378a349e6890a0abd0)

## Context 🤔

Not linked to an issue

## Checklist ✅

- [x] I have reviewed the submitted code
- [x] I have tested on a phone device/emulator

2022-06-02 15:11 UTC, dktbitrise commented
### You can download the apk here :

2022-06-17 11:54 UTC, adrienbusin approved these changes

2022-06-17 13:10 UTC, CorentinStamperDecathlon approved these changes

2022-06-17 13:11 UTC, FDELAHA24 requested changes
Good for me, just very few documentation changes suggestions, Good job !

2022-06-17 13:11 UTC, FDELAHA24 commented on CONVENTIONS.md
> +internal component used. If it is the case, the api slotting should be used to purpose the best
```suggestion
internal component used. If it is the case, the api slotting should be used to offer the best
```

2022-06-24 11:29 UTC, GerardPaligot commented on CONVENTIONS.md
> +following specification for the name `Vitamin<Component><Variant>?Impl`. e.g. `VitaminButtonImpl`
Maybe "Variant" isn't the right name? Maybe something like "Domain" which can mean: "If you component can cover several domains, you can create a common component by domain with the follow specification ..."

2022-06-24 11:30 UTC, GerardPaligot commented on CONVENTIONS.md
> +following specification for the name `Vitamin<Component><Variant>?Impl`. e.g. `VitaminButtonImpl`
e.g: in the appbar, we have the TopAppBar and the BottomAppBar. Of course, you won't have the same common component.

2022-06-24 11:31 UTC, GerardPaligot commented on CONVENTIONS.md
> +        onClick: () -> Unit
This allows you to have this king of usage:
```kotlin
MyComponent {
  // My last parameter is a callback so I can do this kind of thing
}
```

2022-06-24 12:17 UTC, ManonPolle commented on CONVENTIONS.md
> +        onClick: () -> Unit
👍

2022-06-24 13:06 UTC, FDELAHA24 approved these changes

2022-06-24 15:02 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/1456ea14-0cd6-4f27-b49b-a228c769a44d/artifact/02856e3657f54c3f/p/3a9932ad51f2d3250782f2ca7f6888fa

2022-06-24 15:08 UTC, ManonPolle approved these changes

2022-06-24 15:31 UTC, merged