chore(tabs): add paparazzi tests
Decathlon/vitamin-compose pull request #164
Opened 2023-07-07 16:01 UTC by FDELAHA24

## Changes description 🧑‍💻

Add paparazzi tests for tabs 

## Context 🤔

Closes #96 

## Checklist ✅

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review `design-system-core-team-design` GitHub team.

## Screenshots 📸

## Other info 👋

2023-07-07 16:52 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/bc08fbf3-94de-4c44-a75c-3c76b8897872/artifact/082b7f83ce04ef53/p/01984fdb970bb0efd02b2c595afd4a1c

2023-07-12 09:23 UTC, ManonPolle requested changes

2023-07-12 09:23 UTC, ManonPolle commented on tabs/src/test/kotlin/com/decathlon/vitamin/compose/tabs/VitaminButtonsPrimaryTest.kt
> +class VitaminButtonsPrimaryTest(
```suggestion
class VitaminTabsTest(
```

2023-07-13 14:51 UTC, dktbitrise commented
### You can download the apk here :

2023-07-13 15:53 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/808e7afa-a138-42bc-b13c-8e1fb87fecf7/artifact/2e0f5c318d4f7ed1/p/5780eebca18895767fa2c560eb9f0183

2023-07-13 16:30 UTC, ManonPolle approved these changes

2023-07-13 16:38 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/1e06a445-18d3-4c03-ab5b-f3ceaff78751/artifact/d975043c775c0fd2/p/2bddd96d4425caa428a1e32d29e9dd7a

2023-07-17 07:02 UTC, merged