fix(Button): fix icon visibility issue in button when label was too long
Decathlon/vitamin-compose pull request #41
Opened 2022-08-19 13:05 UTC by FDELAHA24

## Changes description 🧑‍💻

The icon was hidden when button label was too long. This contribution fixes this issue.

## Context 🤔

[#37](https://github.com/Decathlon/vitamin-compose/issues/37)

## Checklist ✅

- [ ] Make sure you are requesting to **pull a topic/feature/bugfix branch**. Please, don't request directly from your main!
- [ ] Check commits & PR names matches our requested structure. It must follow the https://www.conventionalcommits.org pattern.
- [ ] Check compose contract convention. It must follow conventions described [here](/CONVENTIONS.md).
- [ ] Check your code additions will fail neither code linting checks.
- [ ] I have reviewed the submitted code.
- [ ] I have tested on a phone device/emulator.
- [ ] I have tested on a tablet device/emulator.
- [ ] I have tested on a large screen device/emulator.
- [ ] If it includes design changes, please ask for a review with a core team designer.

## Screenshots 📸

![Screenshot_20220819_145043](https://user-images.githubusercontent.com/48826368/185624571-c1c36891-31b9-40af-9f91-e2d9aa393547.png)

## Other info 👋

2022-08-19 13:52 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/fcf49764-f1f2-4abd-9e11-953f71b04ea2/artifact/ed1243bb181a2f65/p/679c020a87736b3cb1fd9d4a9c2864d4

2022-08-19 14:33 UTC, ManonPolle submitted a review, later dismissed

2022-08-30 08:19 UTC, GerardPaligot requested changes

2022-08-30 08:19 UTC, GerardPaligot commented on buttons/src/main/java/com/decathlon/vitamin/compose/buttons/VitaminButtons.kt
> +                modifier = Modifier.weight(1f, fill = false),
Because we have already snapshot tests for buttons, that could be great to add this in our current tests no? :)

2022-09-02 13:45 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/186f22df-bf02-4ac8-a063-abb2d07db429/artifact/fb2b402adbab83bd/p/a957b508c3e043459abdc4452f26454e

2022-09-23 13:23 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/4abe7562-1468-4aaf-a735-20d27a1cf565/artifact/e08734d2610e0216/p/db7d089fbbc681462adc194547ed48f4

2022-09-30 11:36 UTC, dktbitrise commented
### You can download the apk here :
**sample-debug.apk :** 
https://app.bitrise.io/app/e9ae480151be4514/build/7fa23301-c42c-4a4d-ace4-4fab2dc34f77/artifact/c5a1c02dfed1db7e/p/058ab571f27f5272c0b09d3f8343bc13

2022-09-30 14:48 UTC, GerardPaligot approved these changes

2022-09-30 14:49 UTC, merged